export const SCREEN = {
  WIDTH: 390,
  HEIGHT: 844,
};

export const BIRD = {
  WIDTH: 44,
  HEIGHT: 32,
  X: 80,
  GRAVITY: 0.6,
  FLAP_FORCE: -10,
  MAX_FALL_SPEED: 12,
  MAX_RISE_SPEED: -12,
};

export const PIPE = {
  WIDTH: 62,
  GAP: 180,
  SPEED: 3,
};

export const GROUND = {
  HEIGHT: 80,
};

export const LEVELS = [
  {
    id: 1,
    name: "NOVICE",
    emoji: "🌱",
    subtitle: "Learn to fly",
    color: "#4ade80",
    pipeSpeed: 2.8,
    pipeGap: 195,
    pipeInterval: 2200,
    gravity: 0.52,
    flapForce: -9.5,
    scoreToUnlock: 0,
    scoreToAdvance: 10,
    bgGradient: ["#87CEEB", "#98D8E8", "#B0E0E6"],
    skyColor: "#87CEEB",
    groundColor: "#90EE90",
  },
  {
    id: 2,
    name: "FLEDGLING",
    emoji: "🐣",
    subtitle: "Getting the hang of it",
    color: "#60a5fa",
    pipeSpeed: 3.4,
    pipeGap: 178,
    pipeInterval: 2000,
    gravity: 0.56,
    flapForce: -10,
    scoreToUnlock: 5,
    scoreToAdvance: 25,
    bgGradient: ["#87CEEB", "#ADD8E6", "#B0E0E6"],
    skyColor: "#87CEEB",
    groundColor: "#98D8C8",
  },
  {
    id: 3,
    name: "AVIATOR",
    emoji: "🦅",
    subtitle: "Soaring higher",
    color: "#f59e0b",
    pipeSpeed: 4.0,
    pipeGap: 162,
    pipeInterval: 1850,
    gravity: 0.60,
    flapForce: -10.5,
    scoreToUnlock: 15,
    scoreToAdvance: 45,
    bgGradient: ["#87CEEB", "#92BEE6", "#A8D8EA"],
    skyColor: "#87CEEB",
    groundColor: "#F0E68C",
  },
  {
    id: 4,
    name: "ACE PILOT",
    emoji: "✈️",
    subtitle: "Master of the skies",
    color: "#f97316",
    pipeSpeed: 4.8,
    pipeGap: 148,
    pipeInterval: 1700,
    gravity: 0.65,
    flapForce: -11,
    scoreToUnlock: 30,
    scoreToAdvance: 70,
    bgGradient: ["#87CEEB", "#87CEFA", "#B0E0E6"],
    skyColor: "#87CEEB",
    groundColor: "#DDA0DD",
  },
  {
    id: 5,
    name: "LEGEND",
    emoji: "👑",
    subtitle: "Defy all limits",
    color: "#e879f9",
    pipeSpeed: 5.8,
    pipeGap: 132,
    pipeInterval: 1550,
    gravity: 0.70,
    flapForce: -11.5,
    scoreToUnlock: 55,
    scoreToAdvance: Infinity,
    bgGradient: ["#87CEEB", "#6495ED", "#B0E0E6"],
    skyColor: "#87CEEB",
    groundColor: "#DDA0DD",
  },
];

export const BIRD_COLORS = [
  { id: "yellow", primary: "#FFD700", secondary: "#FF8C00", name: "Classic" },
  { id: "blue", primary: "#60a5fa", secondary: "#2563eb", name: "Ice" },
  { id: "red", primary: "#f87171", secondary: "#dc2626", name: "Fire" },
  { id: "green", primary: "#4ade80", secondary: "#16a34a", name: "Forest" },
  { id: "purple", primary: "#c084fc", secondary: "#9333ea", name: "Royal" },
];
